### PR TITLE
Added typescript declarations

### PR DESCRIPTION
**Pull request by vadistic**
Hello, I've made typescript declaration files. They should be already ok, but I'll correct them if/when I/somebody else notice some missed detail.

**WHY:**
Needed for myself :)

It's important not just for typescript users - they also add really nice documentation JSDoc documentation for any VSCode user :)

Also - fixes this: https://github.com/neptunian/react-photo-gallery/issues/121

**HOW**
Added as external `types/react-photo-gallery.d.ts` file. I think `index.d.ts` in `dist` dir would have marginally better suport but I would rather not touch your nps build chain.

I can PR them to DefinitelyTyped if you prefer to not deal with declaration file yourself, but current trend seems to be collocation with repos.

Ok?

### CODE REVIEW

**Comment by vadistic** [comment]
I have two more things in mind...

- docs are missing some props for `ImageComponent`

```ts
type ImageComponentClickHandler = (
    event: React.MouseEvent,
    photo: object & {
      index: number
    }
  ) => void

type MissingImageComponentProps = {
  onClick: ImageComponentClickHandler | null
  direction: 'row' | 'column'
  top?: number
  left?: number
  }
```

- I can commit typings with generic type for `photos` props - bit more convoluted but can easily be used to create interface with arbitrary photos object.

Use case (i.e. with `gatsby-images`):

```ts
import _Gallery, { GalleryI } from 'react-photo-gallery'

type CustomPhotoProps = {
  // let's make scrSet required string
   scrSet: string
  // let's add aspect ratio
   aspectRatio: number
}

// tada!
const Gallery = _Gallery as GalleryI<CustomPhotoProps>

// without this custom props generally require retyping whole thing
```

The typings would look like that (I hope it's not too long to paste it :smile: )
```ts
declare module 'react-photo-gallery' {
  import React from 'react'

  /**
   * Photos array item properties (passed into Gallery's photos property)
   */
  export type PhotoProps<CustomPhotoProps extends object = unknown> = {
    /**
     * the img src attribute value of the image
     */
    src: string
    /**
     * srcSet attribute of the image
     */
    srcSet?: string | string[]
    /**
     * sizes attribute of the image
     */
    sizes?: string | string[]
    /**
     *  original width of the gallery image (only used for calculating aspect ratio)
     */
    width: number
    /**
     *  original height of the gallery image (only used for calculating aspect ratio)
     */
    height: number
    /**
     *  alt text of the gallery image
     */
    alt?: string
    /**
     * key to be used on component
     * @default
     * src
     */
    key?: string
  } & CustomPhotoProps

  export type ImageComponentClickHandler = (
    event: React.MouseEvent,
    photo: object & {
      index: number
    }
  ) => void

  /**
   * If you're passing a function component to ImageComponent you will receive back these props:
   */
  export interface ImageComponentProps<
    CustomPhotoProps extends object = unknown
  > {
    /**
     * margin prop optionally passed into Gallery by user
     */
    margin?: string
    /**
     * the index of the photo within the Gallery
     */
    index: number
    /**
     * the individual object passed into Gallery's
     * photos array prop, with all the same props except recalculated height and width
     */
    photo: PhotoProps<CustomPhotoProps>

    onClick: ImageComponentClickHandler | null
    direction: 'row' | 'column'
    top?: number
    left?: number
  }

  export type PhotoClickHandler<CustomPhotoProps extends object = unknown> = (
    event: React.MouseEvent,
    photos: {
      index: number
      next: PhotoProps<CustomPhotoProps> | null
      photo: PhotoProps<CustomPhotoProps>
      previous: PhotoProps<CustomPhotoProps> | null
    }
  ) => void

  export interface GalleryProps<CustomPhotoProps extends object = unknown> {
    photos: Array<PhotoProps<CustomPhotoProps>>
    /**
     * number of photos per row or a function which receives the container width
     * and should return the desired number of photos per row; defaults to Gallery's breakpoint choosing
     */
    columns?: number | ((containerWidth: number) => number)
    /**
     * do something when the user clicks a photo;
     * receives arguments event and an object containing the index,
     * photo obj originally sent and the next and previous photos in the gallery if they exist
     */
    onClick?: PhotoClickHandler<CustomPhotoProps>

    /**
     * number of margin pixels around each entire image
     * @default 2
     */
    margin?: number
    /**
     * column or row based layout
     * @default'row'
     */
    direction?: string

    ImageComponent?: React.ComponentType<ImageComponentProps<CustomPhotoProps>>
  }

  export type GalleryI<
    CustomPhotoProps extends object = unknown
  > = React.ComponentClass<GalleryProps<CustomPhotoProps>>

  declare const Gallery: GalleryI

  export default Gallery
}
```

**Comment by neptunian** [comment]
What do you mean by "docs are missing some props for ImageComponent" and why do you have a typed called MissingImageComponentProps. Otherwise i think it looks good if you want to update the commit to the second version you copied?

**Comment by vadistic** [comment]
> What do you mean by "docs are missing some props for ImageComponent"

Documentation [here - bottom of the page](http://neptunian.github.io/react-photo-gallery/) specify `ImageComponent` - I thought four of them were missing , but I see them there now (either you added or my brainfart), nevermind

> why do you have a typed called MissingImageComponentProps.

Just to list the props mentioned above, nothing more.

> What is the point of the CustomPhotosProps? Any props you don't see currently in the docs are not passed through so why would they pass in custom photo props?

I've meant - the `Image component` receive all props (except `containerHeight`) of `photos` array element from `Gallery` component as `photo` prop. See here: https://github.com/neptunian/react-photo-gallery/blob/master/src/Gallery.js#L78-L89

So the point of `CustomPhotoProps` is that if my `photos` array of object (in docs as *Photos array item properties (passed into Gallery's photos property)*)  must ofc conform those requirements, BUT I may want to specify some other required/optional props.

From example above:

```ts
type CustomPhotoProps = {
  // I need to make scrSet required (because my customImageComponent will need it)
   scrSet: string
  // I need prop aspectRatio for the same reason (and it will get passed)
   aspectRatio: number
}
```
So then I can do:

```ts
// my gallery will require now that photos prop will contain my extra properties
const Gallery = _Gallery as GalleryI<CustomPhotoProps>

// my Image Component will have corect typings for buildin and custom props
const ImageComponent: React.FC<ImageComponentProps<CustomPhotoProps>>  = (props) => (
// render stuff
)
```

The use of whole generic is optional for the end user, because I've provided default parameter. You can also do without it, but  it's a bit more complicated and I thought I'm making things easier for users newer to typescript. Just decide if you want the generics or not - I would add them because it's not breaking api in any way)
```ts
type CustomGalleryPhotoProps = {
  photos: CustomPhotoProps
  ImageComponent: React.ComponentType<ImageComponentProps & CustomPhotoProps>

}

const Gallery = _Galerry as React.ComponentType<GalleryProps & CustomGalleryPhotoProps> 

const ImageComponent: React.FC<ImageComponentProps & CustomPhotoProps >  = (props) => (
// render stuff
)

```

**Comment by vadistic** [comment]
Just as reference why I brought up whole custom photo props thing (feel free to skip it) - here's my code where I needed custom photo prop to use `gatsby-image` component:

https://github.com/vadistic/generic-portfolio-starter/blob/master/src/components/gallery.tsx

**Comment by neptunian** [comment]
Sorry you're right. I missed where "rest" is getting passed thru to the photo object so, yes, the generic type would be welcome.  Did you want to update the PR and then I can merge it?  Thanks again!

**Comment by neptunian** [comment]
If you'd like I can merge your changes and then add the missing types and generics myself.

**Comment by vadistic** [comment]
Sorry to keep you waiting.

To detail changes:
1) `import * as React from 'react'` to support weirder tsconfigs.
2) `{}` insted of `unknown` to not add unnecessary typescript 3.0 requirement.

Good to go I think.

**Comment by neptunian** [comment]
Sorry, was on vacation for a while.  I tried testing this out. I notice I can type something like this and there are no errors.  It says "any" is allowed? 
screen shot 2019-02-18 at 3 33 30 pm

**Comment by ngbrown** [comment]
This doesn't seem to be working in TypeScript 3.7.5.  My code looks like this:

```ts
import _Gallery, {GalleryI} from "react-photo-gallery";
type CustomPhotoProps = {loading: string};
const Gallery = _Gallery as GalleryI<CustomPhotoProps>;
```

Then the compiler error:


> Error:(12, 17) TS2352: Conversion of type 'GalleryI<{}>' to type 'GalleryI<CustomPhotoProps>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
>   Types of parameters 'props' and 'props' are incompatible.
>     Type 'GalleryProps<CustomPhotoProps>' is not comparable to type 'GalleryProps<{}>'.
>       Type '{}' is not comparable to type 'CustomPhotoProps'.

**Edit**: never-mind, the additional properties seem to need to be optional.

This worked:

```ts
type CustomPhotoProps = {loading?: string};
```

**Comment by MiadV** [comment]
would be nice to mention this in the read-me

**Pull request merged**
