### PR TITLE
Feature/thumbnails

### PR DESCRIPTION
**Pull request by slorenzo**
## Proposal Changes

- Set thumbnails as an **option**.

- Each image can have a thumbnail to show in the gallery.

- If the user needs to show the full images, they can use `react-images` as @neptunian explain in the examples.

- Test improvements

Hope it helps you.

### CODE REVIEW

**Comment by neptunian** [comment]
not sure i understand why thumbnail would be an option

**Comment by slorenzo** [comment]
To show a crop of the images in the grid. When the user tap on an image, you can show the full image using `react-images` library. Of course, it's optional.

**Comment by neptunian** [comment]
what is a "crop of the images"?

**Comment by neptunian** [comment]
oh you want to pass in a smaller image called thumbnail?  the idea is that the image you pass in should be the one you display in the gallery, so that is, be default, the thumbnail.  if you want to pass in a larger image for react-images you can do so in your own app.

**Comment by slorenzo** [comment]
Yes, but this feature allows you to have a thumbnail to display in the gallery and larger image for react-images using the same object. Thumbnails field overrides src image on this library but still working on react-images.

**Comment by neptunian** [comment]
as i said the images you provide to the photo gallery are intended to be the thumbnail image in the first place.  if you wish to provider a higher resolution image for a photo viewer, such as react-images, that is something you would pass to that component in your own app.

**Pull request closed without merging**
