### PR TITLE
Added a User Guide section to the Readme file

### PR DESCRIPTION
**Pull request by dmr**
How do you feel about adding this section?
Reading issues and solutions is ok for existing users but new users could have an easier start by having a section where we summarize how things could be done

### CODE REVIEW

**Comment by neptunian** [comment]
Sure, that's a great idea.  Although maybe we should clarify that is part of the app file and not the component itself?  Like how the Gallery could be used.

**Comment by iMerica** [comment]
👍  LGTM

**Comment by neptunian** [comment]
I think maybe Demo Explanation and User Guide / Best Practice should be under the same section

**Comment by dmr** [comment]
I agree. Also, there should be a sentence about the Lightbox split and best practice to use it in combination.

**Pull request merged**
