### PR TITLE
Stateless gallery

### PR DESCRIPTION
**Pull request by neptunian**
related to issue #13  and issue #20

### CODE REVIEW

**Comment by smeijer** [comment]
We can re-use the `PHOTO_SET` and drop `LIGHTBOX_IMAGE_SET` if we just add `caption` and `srcset` to `PHOTO_SET`.

The current idea is that `PHOTO_SET.src` has a smaller image than `LIGHTBOX_IMAGE_SET.src`, but that should be something that the `srcset` takes care of.

If we really care about having a separate `LIGHTBOX_IMAGE_SET`, than I would make it optional. With:

```js
images = lightboxOptions.images || photos;
```

This simplifies the API, because we only need to provide a single image source, and improves accessibility, when we set the caption as title attribute on the gallery thumb. 

Not to forget that with this change, the gallery also has support for progressive enhancement of image resolutions trough the availability of a srcset.

**Comment by neptunian** [comment]
@smeijer  thanks for you comments.

The thing about combing the lightbox image set into photoset... One user has also requested the ability to add a seprate "srcset" and "sizes" attributes to the Gallery img tag.  So i want "srcset" attributes to be custom for both the Gallery photo and the Lightbox photo. But i think you are right in the sense that the same value for srcset can be used for both img elements with the user keeping in mind the range of sizes needed. I could have a condition where if the user does decide to pass in the 'images' option i'll use it otherwise i wont?

Also can you read Gregory's comments and concerns and let me know what you think? https://github.com/neptunian/react-photo-gallery/issues/13#issuecomment-282700886

**Comment by neptunian** [comment]
@smeijer  @GregoryPotdevin Please look at the latest commit where I just removed Lightbox from the gallery altogether and put it in the app.  It seems to be working fine.  I think this is great, the user can use whatever lightbox they might want or not use one at all.  Then the Gallery can focus on being a Gallery component.

**Comment by GregoryPotdevin** [comment]
Looks good. You can make the code slightly shorter with something like this : 
```js
if (this.state.photos) {
  return (
    <div className="App">
      {this.renderGallery()}
      <Lightbox
        images={this.state.lightboxImages}
        backdropClosesModal={true}
        onClose={this.closeLightbox}
        onClickPrev={this.gotoPrevious}
        onClickNext={this.gotoNext}
        currentImage={this.state.currentImage}
        isOpen={this.state.lightboxIsOpen}
        width={1600}
      />
      {!this.state.loadedAll && <div className="loading-msg" id="msg-loading-more">Loading</div>}
    </div>
  );
}
else {
  return (
    <div className="App">
      <div id="msg-app-loading" className="loading-msg">Loading</div>
    </div>
  );
}
```

**Comment by neptunian** [comment]
@GregoryPotdevin  thanks!  What do you think?  Is it the best thing to do in thend?  I know it means no built in lightbox but it really opens a lot of doors for what the user can do to the Gallery.

**Comment by GregoryPotdevin** [comment]
The React ecosystem greatly favors components that compose well, so removing the Lightbox goes in that direction (Gallery would compose with this Lightbox or other ones).

**Comment by neptunian** [comment]
Hey @GregoryPotdevin and @smeijer .  Please see the latest commit where I have incorporated both of your suggestions.

**Pull request merged**
