### PR TITLE
Extract breakpointsConfig as separate prop with default value

### PR DESCRIPTION
**Pull request by RZhosan**
Extracted breakpoints configuration as a separate prop in order to be able to modify it.

### CODE REVIEW

**Comment by neptunian** [comment]
i prefer to leave it as is and let users pass in the columns with their own config such as in the example: https://codesandbox.io/s/ll7ym48027

**Comment by RZhosan** [comment]
But wouldn't it be better and cleaner to use the behaviour provided by your components, rather than using of additional wrapping of Gallery with Measure component?

**Comment by neptunian** [comment]
I think if they want to override the default they can keep track of the state in their app and pass it down to the Gallery when it re renders and gives them full control as to how they want to compute the columns.  I think it's cleaner this way.

**Comment by RZhosan** [comment]
Keep track on the width of your component and do the same things you're already doing? :)

What do you think, do you lose something from the extracting of breakpoints configuration into the props with default value, rather than hard coded usage of it the render method?

But do you gain something? I think yes, because it makes your component more configurable without any external tools and without any extra efforts from your side.

As for me, I would appreciate your component be able to adjust image sizes based on its width without any external tools/code and using only the configuration passed as a prop.

**Comment by neptunian** [comment]
I'll consider it for a future release, but I prefer to leave it as is for now.

**Comment by RZhosan** [comment]
Ok, np.

**Pull request closed without merging**
